[[files]]
source = '../../../../files/of-root/at-belphegor/refind/refind.conf'
target = '/boot/EFI/refind/refind.conf'
action = 'copy'
chmod = '644'
owner = 'root'
group = 'root'
profiles = ['root@belphegor']

[[files]]
source = '../../../../files/of-root/at-belphegor/refind/extra.conf'
target = '/boot/EFI/refind/extra.conf'
action = 'copy'
chmod = '644'
owner = 'root'
group = 'root'
profiles = ['root@belphegor']
