[[files]]
source = '../../files/of-root/at-uriel/refind/refind.conf'
target = '/boot/EFI/refind/refind.conf'
action = 'copy'
chmod = '644'
owner = 'root'
group = 'root'
profiles = ['root@uriel']

[[files]]
source = '../../files/of-root/at-uriel/refind/extra.conf'
target = '/boot/EFI/refind/extra.conf'
action = 'copy'
chmod = '644'
owner = 'root'
group = 'root'
profiles = ['root@uriel']
