[[files]]
source = '../../files/of-bluewy/at-raphael/applications/heroic.desktop'
target = '/home/bluewy/.local/share/applications/heroic.desktop'
action = 'link'
chmod = '644'
owner = 'bluewy'
group = 'bluewy'
profiles = ['bluewy@raphael', 'bluewy@uriel']

[[files]]
source = '../../files/of-bluewy/at-raphael/applications/obs.desktop'
target = '/home/bluewy/.local/share/applications/obs.desktop'
action = 'link'
chmod = '644'
owner = 'bluewy'
group = 'bluewy'
profiles = ['bluewy@raphael', 'bluewy@uriel']

[[files]]
source = '../../files/of-bluewy/at-raphael/applications/osu-lazer.desktop'
target = '/home/bluewy/.local/share/applications/osu-lazer.desktop'
action = 'link'
chmod = '644'
owner = 'bluewy'
group = 'bluewy'
profiles = ['bluewy@raphael', 'bluewy@uriel']
