[[files]]
source = '../../../../files/of-bluewy/at-raphael/bin/customizer'
target = '/home/bluewy/.local/bin/customizer'
action = 'link'
chmod = '744'
owner = 'bluewy'
group = 'bluewy'
profiles = ['bluewy@raphael', 'bluewy@uriel']

[[files]]
source = '../../../../files/of-bluewy/at-raphael/bin/wmd-helper'
target = '/home/bluewy/.local/bin/wmd-helper'
action = 'link'
chmod = '744'
owner = 'bluewy'
group = 'bluewy'
profiles = ['bluewy@raphael', 'bluewy@uriel']

[[files]]
source = '../../../../files/of-bluewy/at-raphael/bin/cgl'
target = '/home/bluewy/.local/bin/cgl'
action = 'link'
chmod = '744'
owner = 'bluewy'
group = 'bluewy'
profiles = ['bluewy@raphael', 'bluewy@uriel']

# # #

[[files]]
source = '../../../../files/of-bluewy/at-raphael/bin/wmd-helper'
target = '/home/kuroka/.local/bin/wmd-helper'
action = 'link'
chmod = '744'
owner = 'kuroka'
group = 'kuroka'
profiles = ['kuroka@raphael']
