[[files]]
source = '../../../../files/of-bluewy/at-raphael/electron/electron-flags.conf'
target = '/home/bluewy/.config/electron-flags.conf'
action = 'link'
chmod = '644'
owner = 'bluewy'
group = 'bluewy'
profiles = ['bluewy@raphael', 'bluewy@uriel']

[[files]]
source = '../../../../files/of-bluewy/at-raphael/electron/electron-flags.conf'
target = '/home/kuroka/.config/electron-flags.conf'
action = 'link'
chmod = '644'
owner = 'kuroka'
group = 'kuroka'
profiles = ['kuroka@raphael']
