[[files]]
source = '../../../files/of-bluewy/at-raphael/fastfetch'
target = '/home/bluewy/.config/fastfetch'
action = 'link'
chmod = '755'
owner = 'bluewy'
group = 'bluewy'
profiles = ['bluewy@raphael', 'bluewy@uriel', 'bluewy@sariel']

[[files]]
source = '../../../files/of-bluewy/at-raphael/fastfetch'
target = '/home/yellowy/.config/fastfetch'
action = 'link'
chmod = '755'
owner = 'yellowy'
group = 'yellowy'
profiles = ['yellowy@uriel']

[[files]]
source = '../../../files/of-bluewy/at-raphael/fastfetch'
target = '/home/kuroka/.config/fastfetch'
action = 'link'
chmod = '755'
owner = 'kuroka'
group = 'kuroka'
profiles = ['kuroka@raphael']
