[[files]]
source = '../../files/of-bluewy/at-raphael/hypr'
target = '/home/bluewy/.config/hypr'
action = 'link'
chmod = '755'
owner = 'bluewy'
group = 'bluewy'
profiles = ['bluewy@raphael', 'bluewy@uriel']
