[[files]]
source = '../../files/of-bluewy/at-raphael/libinput/local-overrides.quirks'
target = '/etc/libinput/local-overrides.quirks'
action = 'copy'
chmod = '644'
owner = 'root'
group = 'root'
profiles = ['root@raphael', 'root@uriel', 'root@sariel', 'root@belphegor']
