[[files]]
source = '../../files/of-bluewy/at-raphael/librewolf/librewolf.overrides.cfg'
target = '/home/bluewy/.librewolf/librewolf.overrides.cfg'
action = 'link'
chmod = '644'
owner = 'bluewy'
group = 'bluewy'
profiles = ['bluewy@raphael', 'bluewy@uriel']
