[[files]]
source = '../../../../files/of-bluewy/at-raphael/matugen'
target = '/home/bluewy/.config/matugen'
action = 'link'
chmod = '755'
owner = 'bluewy'
group = 'bluewy'
profiles = ['bluewy@raphael', 'bluewy@uriel']

# # #

[[files]]
source = '../../../../files/of-bluewy/at-raphael/matugen'
target = '/home/kuroka/.config/matugen'
action = 'link'
chmod = '755'
owner = 'kuroka'
group = 'kuroka'
profiles = ['kuroka@raphael']
