[[files]]
source = '../../files/of-bluewy/at-raphael/niri'
target = '/home/bluewy/.config/niri'
action = 'link'
chmod = '755'
owner = 'bluewy'
group = 'bluewy'
profiles = ['bluewy@raphael', 'bluewy@uriel']

[[files]]
source = '../../files/of-bluewy/at-raphael/niri'
target = '/home/kuroka/.config/niri'
action = 'link'
chmod = '755'
owner = 'kuroka'
group = 'kuroka'
profiles = ['kuroka@raphael']
