[[files]]
source = '../../../../files/of-bluewy/at-raphael/pipewire'
target = '/home/bluewy/.config/pipewire'
action = 'link'
chmod = '755'
owner = 'bluewy'
group = 'bluewy'
profiles = ['bluewy@raphael', 'bluewy@uriel']

[[files]]
source = '../../../../files/of-bluewy/at-raphael/pipewire'
target = '/home/kuroka/.config/pipewire'
action = 'link'
chmod = '755'
owner = 'kuroka'
group = 'kuroka'
profiles = ['kuroka@raphael']
