[[files]]
source = '../../files/of-bluewy/at-raphael/starship/starship.toml'
target = '/home/bluewy/.config/starship.toml'
action = 'link'
chmod = '644'
owner = 'bluewy'
group = 'bluewy'
profiles = ['bluewy@raphael', 'bluewy@uriel', 'bluewy@sariel']

[[files]]
source = '../../files/of-bluewy/at-raphael/starship/starship.toml'
target = '/home/yellowy/.config/starship.toml'
action = 'link'
chmod = '644'
owner = 'yellowy'
group = 'yellowy'
profiles = ['yellowy@uriel']
