[[units]]
user = 'root'
enable = [
   'getty@tty1.service',

   'systemd-networkd.service',
   'systemd-resolved.service',
   'iwd.service',

   'systemd-timesyncd.service',

   'bluetooth.service',

   'ufw.service',
   'ananicy-cpp.service',

   'lactd.service',
]
profiles = ['root@raphael']
