[[packages]]
install = [
   { from = 'std', name = 'power-profiles-daemon' },
   { from = 'std', name = 'python-gobject' },

   { from = 'std', name = 'wiremix' },
   { from = 'std', name = 'bluetui' },

   { from = 'std', name = 'bottom' },
   { from = 'std', name = 'bandwhich' },
   { from = 'std', name = 'nvtop' },
]
profiles = ['root@raphael', 'root@uriel', 'root@sariel', 'root@belphegor']
