[[files]]
source = '../../../files/of-root/at-raphael/locale/locale.gen'
target = '/etc/locale.gen'
action = 'copy'
chmod = '655'
owner = 'root'
group = 'root'
profiles = ['root@raphael', 'root@uriel', 'root@sariel', 'root@belphegor']

[[files]]
source = '../../../files/of-root/at-raphael/locale/locale.conf'
target = '/etc/locale.conf'
action = 'copy'
chmod = '655'
owner = 'root'
group = 'root'
profiles = ['root@raphael', 'root@uriel', 'root@sariel', 'root@belphegor']
