[[files]]
source = '../../../../files/of-root/at-raphael/logind/big-runtime.conf'
target = '/etc/systemd/logind.conf.d/big-runtime.conf'
action = 'copy'
chmod = '644'
owner = 'root'
group = 'root'
profiles = ['root@raphael', 'root@uriel', 'root@sariel']
