[[files]]
source = '../../../../files/of-root/at-raphael/networkd/20-wired.network'
target = '/etc/systemd/network/20-wired.network'
action = 'copy'
chmod = '655'
owner = 'root'
group = 'root'
profiles = ['root@raphael']

[[files]]
source = '../../../../files/of-root/at-raphael/networkd/21-wireless.network'
target = '/etc/systemd/network/21-wireless.network'
action = 'copy'
chmod = '655'
owner = 'root'
group = 'root'
profiles = ['root@raphael']
