[[files]]
source = '../../../files/of-root/at-raphael/psd/frequency.conf'
target = '/etc/systemd/user/psd-resync.timer.d/frequency.conf'
action = 'copy'
chmod = '644'
owner = 'root'
group = 'root'
profiles = ['root@raphael', 'root@uriel', 'root@sariel']
