[[files]]
source = '../../../../files/of-root/at-uriel/resolved/resolved.conf'
target = '/etc/resolved.conf'
action = 'copy'
chmod = '655'
owner = 'root'
group = 'root'
profiles = ['root@raphael', 'root@uriel', 'root@sariel', 'root@belphegor']
