[[files]]
source = '../../../../files/of-root/at-raphael/rtcwake-for-mc-server-service/do-rtcwake-for-mc-server'
target = '/usr/local/bin/do-rtcwake-for-mc-server'
action = 'copy'
chmod = '744'
owner = 'root'
group = 'root'
profiles = []

[[files]]
source = '../../../../files/of-root/at-raphael/rtcwake-for-mc-server-service/rtcwake-for-mc-server.timer'
target = '/etc/systemd/user/rtcwake-for-mc-server.timer'
action = 'copy'
chmod = '644'
owner = 'root'
group = 'root'
profiles = []

[[files]]
source = '../../../../files/of-root/at-raphael/rtcwake-for-mc-server-service/rtcwake-for-mc-server.service'
target = '/etc/systemd/user/rtcwake-for-mc-server.service'
action = 'copy'
chmod = '644'
owner = 'root'
group = 'root'
profiles = []
