[[files]]
source = '../../files/of-root/at-raphael/vconsole/vconsole.conf'
target = '/etc/vconsole.conf'
action = 'copy'
chmod = '655'
owner = 'root'
group = 'root'
profiles = ['root@raphael', 'root@uriel', 'root@sariel']
