[[units]]
user = 'bluewy'
path = '/home/bluewy/.config/systemd/user'
mask = ['xdg-user-dirs.service', 'at-spi-dbus-bus.service']
enable = ['wireplumber.service', 'pipewire.service', 'psd.service', 'xwayland-satellite-in-niri-custom.service', 'noctalia-in-niri-custom.service']
profiles = ['bluewy@raphael', 'bluewy@uriel']
