[[packages]]
install = [
   { from = 'aur', name = 'vscodium-bin-marketplace' },

   { from = 'aur', name = 'obs-pipewire-audio-capture-bin' },
   { from = 'std', name = 'obs-studio' },

   { from = 'std', name = 'audacity' },
   { from = 'std', name = 'krita' },
   { from = 'std', name = 'kdenlive' },

   { from = 'std', name = 'onlyoffice-bin' },
]
profiles = ['root@raphael', 'root@uriel']
