[[packages]]
install = [
   { from = 'std', name = 'librewolf-bin' },
   { from = 'aur', name = 'profile-sync-daemon-librewolf' },
   { from = 'std', name = 'thunderbird' },
]
profiles = ['root@raphael', 'root@uriel']
