[[packages]]
install = [
   { from = 'std', name = 'rust' },
   { from = 'std', name = 'jdk21-openjdk' },

   { from = 'std', name = 'bun-bin' },

   { from = 'std', name = 'git' },
   { from = 'std', name = 'less' },
]
profiles = ['root@raphael', 'root@uriel', 'root@sariel', 'root@belphegor']
