[[packages]]
install = [
   { from = 'lcl', name = 'profile-sync-daemon-librewolf', path = '../../../../pkgbuilds/profile-sync-daemon-librewolf' },
   { from = 'std', name = 'thunderbird' },
]
profiles = ['root@raphael', 'root@uriel']
