[config]

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/gtk.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.qt5ct]
input_path = './templates/qtct.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = './templates/qtct.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.kcolorscheme]
input_path = './templates/kcolorscheme.colors'
output_path = '~/.local/share/color-schemes/matugen.colors'

[templates.noctalia]
input_path = './templates/noctalia-colors.json'
output_path = '~/.config/noctalia/colors.json'
