[[files]]
source = '../../files/of-root/at-sariel/lenovo-battery-limit-service/limit-lenovo-battery'
target = '/usr/local/bin/limit-lenovo-battery'
action = 'copy'
chmod = '744'
owner = 'root'
group = 'root'
profiles = ['root@sariel']

[[files]]
source = '../../files/of-root/at-sariel/lenovo-battery-limit-service/lenovo-battery-limiter.service'
target = '/etc/systemd/lenovo-battery-limiter.service'
action = 'copy'
chmod = '644'
owner = 'root'
group = 'root'
profiles = ['root@sariel']
