[[files]]
source = '../../../files/of-root/at-sariel/refind/refind.conf'
target = '/boot/EFI/refind/refind.conf'
action = 'copy'
chmod = '644'
owner = 'root'
group = 'root'
profiles = ['root@sariel']

[[files]]
source = '../../../files/of-root/at-sariel/refind/extra.conf'
target = '/boot/EFI/refind/extra.conf'
action = 'copy'
chmod = '644'
owner = 'root'
group = 'root'
profiles = ['root@sariel']
